# Generated by Django 4.1.7 on 2023-04-20 05:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0037_alter_projectsmodel_projecttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('Client', models.TextField(default=None)),
                ('ProcessName', models.TextField(default=None)),
                ('Role', models.TextField(default=None)),
                ('Duration', models.TextField()),
                ('Tools', models.TextField()),
                ('comments1', models.TextField(default=None, null=True)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=None, null=True), size=5), size=5)),
                ('projectdetails_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.projectsmodel')),
            ],
            options={
                'db_table': 'Projectdetails',
            },
        ),
    ]
