# Generated by Django 4.1.7 on 2023-04-22 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0049_alter_projectdetailsmodel_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('books', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), size=None)),
            ],
        ),
    ]
