# Generated by Django 4.1.7 on 2023-04-22 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0050_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=[], size=None),
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
    ]
