# Generated by Django 4.1.7 on 2023-04-22 06:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0051_alter_author_books_alter_author_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), size=None),
        ),
    ]
