# Generated by Django 4.1.7 on 2023-04-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0052_alter_author_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
