# Generated by Django 4.1.7 on 2023-04-22 06:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0054_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetailsmodel',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=None, null=True), size=5),
        ),
    ]
