# Generated by Django 4.1.7 on 2023-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0055_alter_projectdetailsmodel_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Author_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
