# Generated by Django 4.1.7 on 2023-04-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0056_remove_author_author_id_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
    ]
