# Generated by Django 4.1.7 on 2023-04-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0057_alter_author_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RPAResume.projectsmodel'),
        ),
    ]
