# Generated by Django 4.1.7 on 2023-04-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPAResume', '0058_author_author_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorModel',
        ),
    ]
